package model;

import java.io.Serializable;
import java.util.List;

public class Item implements Serializable {
    public String name;
    private int cost;
    private double income;
    List<Upgrade> applicableUpgrades;
    List<Upgrade> purchasedUpgrades;


    //EFFECTS: creates an item
    public Item(String name, int cost, double income, List<Upgrade> upgrades) {
        this.name = name;
        this.cost = cost;
        this.income = income;
        this.applicableUpgrades = upgrades;
    }

    //EFFECTS: returns the income generated by the item
    public double getIncome() {
        return income;
    }

    //EFFECTS: returns the cost of the item
    public int getCost() {
        return cost;
    }

    //REQUIRES: upgrade is in applicableUpgrades
    //MODIFIES: this
    //EFFECTS: adds the upgrade to the item
    public void addUpgrade(Upgrade u) {
        purchasedUpgrades.add(u);
        income = u.applyUpgrade(income);
    }
}
